services:
    redis:
        image: redis:alpine
        container_name: bear-redis

    db:
        ports:
            - "3306:3306"
        image: mysql:5.7
        container_name: bear-db
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
        volumes:
            - bear-db58:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=bear
            - MYSQL_USER=bear
            - MYSQL_PASSWORD=bear

    php-fpm:
      container_name: bear-php-fpm
      build: ./
      environment:
        COMPOSER_HOME: /app
      ports:
        - "9001:9001"
      depends_on:
        - db
      volumes:
        - .:/app
        - ./.docker/queues.conf:/etc/supervisor/conf.d/queues.conf

    rabbitmq:
      container_name: bear-rabbitmq
      image: 'rabbitmq:3.12.2-management'
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - rabbitmq:/var/lib/rabbitmq:cached
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_LOGS: /var/log/rabbitmq/log/all-logs

    nginx:
      container_name: bear-nginx
      image: nginx:stable-alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - .:/app:ro
        - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - php-fpm

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
    bear-db58:
    rabbitmq:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
