controllers:
    resource:
        path: ../src/Adapter/Primary/Http/Controller/
        namespace: App\Adapter\Primary\Http\Controller
    type: attribute
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.api:
    prefix: /_/api
    resource:
        path: ../src/Adapter/Primary/Http/Controller/Api/
        namespace: App\Adapter\Primary\Http\Controller\Api
    type: attribute
